[package]
name = "devkit-postgres"
description = "The Postgres connection devkit's database-backed stores share"
edition.workspace = true
version = "0.14.11" # x-release-please-version

[dependencies]
anyhow.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
tokio-postgres-rustls.workspace = true
devkit-common.workspace = true
