[package]
name = "devkit-testtmp"
description = "Self-cleaning scratch directories for devkit's tests"
edition.workspace = true
version = "0.1.0" # x-release-please-version
license = "GPL-3.0-or-later"
repository = "https://github.com/AbysmalBiscuit/devkit"
publish = false

[dependencies]
tempfile.workspace = true
